[[section-solution-strategy]]
== Lösungsstrategie
//https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_understand_architecture_and_workflow.md
//https://github.com/ApolloAuto/apollo/tree/master/modules/common/proto Kommunikationsprotokolle als Protobuf, mit welchen Fehler, Richtungen etc. kommuniziert werden.
//https://github.com/ApolloAuto/apollo/tree/master/modules/canbus Kommunikation im CAN-Bus
[role="arc42help"]
****
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.

C++ und Python zur Integration: Für anwendungsorientierte Programmierer aus dem Maschinenbau/der Fahrzeugtechnik und für klassiche Informatiker geeignet

****
