[[section-solution-strategy]]
== Lösungsstrategie



[role="arc42help"]

===Einstieg

[cols="1,2" options="header"]
|===
|Qualitätsziel | Dem zuträgliche Ansätze in der Architektur
| _Schnelle Entwicklung autonomer Fahrzeuge_ | _Cyber RT Framework; Definierte Schnittstellen (mit Bild vom technischen Kontext Vorkapitel, wo diese sind)_
| _Schnelle Tests von autonomen Fahrzeugen_ | _Tests vor der Integration ins Fahrzeug? - CyberRT?_
| _Flexible Architektur_ | _Continious Integration Ansatz, Upload auf Github; Erweiterbarkeit?;_
| _Verständliche Darstellung_ | _Implementationsbeschreibung über Readme-Dateien in der Repository. Darüber auch zusätzliche Informationen zum Aufbau der Funktionen._
|===

===Aufbau

Unterteilung der verschiedenen Funktionen: Perceiption, Sensoring, Mapping, .....

===Aufbau2

//https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_understand_architecture_and_workflow.md !!!
//rpc, nicht grpc, aufpassen mit ROS, neues system, 
//Verweis auf:
//https://github.com/ApolloAuto/apollo/tree/master/modules/common/proto Kommunikationsprotokolle als Protobuf, mit welchen Fehler, Richtungen etc. kommuniziert werden.

//Informationen zur Fahrzeugaktiorik:
//https://github.com/ApolloAuto/apollo/tree/master/modules/canbus Kommunikation im CAN-Bus

===Anbindung

Wie programmiere ich und wie greife ich auf Schnittstellen zu? Wie kann ich selbst geschriebnene Programmcode zum System beitragen?

****
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.

C++ und Python zur Integration: Für anwendungsorientierte Programmierer aus dem Maschinenbau/der Fahrzeugtechnik und für klassiche Informatiker geeignet

****
