[[section-design-decisions]]
== Entwurfsentscheidungen

Im folgenden Kapitel wird eine interessante Entscheidung im Entwicklungsverlauf des Projektes genauer betrachtet


=== ROS vs CyberRT

.Fragestellung
Zur Entwicklung eines autonom fahrenden Fahrzeugs muss festgelegt werden, mithilfe welches Frameworks dies umgesetzt wird.
Dieses muss verschiedene Funktionen umfassen und eine Programmbibliothek liefern, welche für diesen Anwendungsfall geeignet ist.

.Relevante Einflussfaktoren
* Funktionsumfang
* Programmbibliothek
* Anforderungen des Zielsystems

.Alternative: ROS

Zum Beginn der Erarbeitung autonomer Fahrzeuge wurde als Framework ROS verwendet.
Dieses, ursprünglich für Roboter entwickelte Framework (Robot Operating System) bietet grundlegende Funktionen und Bibliotheken, die für die Entwicklung technischer Anwendungen notwendig waren.
Es zeichnet sich durch hohe Flexibilität aus, kommt jedoch bei Echtzeit-Anforderungen an seine Grenzen.
Es ermöglicht eine Programmierung in Python und C++ und stellt somit eine gute Grundlage für die Entwicklung eigener Systeme dar.

Bei der Zielsetzung, Level 4 autonomes Fahren umzusetzen, hat man sich jedoch aufgrund der fehlenden Berücksichtigung von Echtzeitanforderungen und einer Bibliothek,
die nicht dediziert für autonomes Fahren entwickelt wurde, gegen eine Weiterverwendung von ROS entschieden.

<<<<

.Entscheidung: Entwicklung des eigenen Frameworks CyberRT

Mit Apollo 3.5 wurde das eigens von Baidu entwickelte Framework CyberRT eingeführt.
Diese auf hohe Performance ausgerichtete Umgebung, die explizit für das autonome Fahren entwickelt wurde, zeichnet sich durch hohe Nebenläufigkeit, geringe Latenz und hohen Datendurchsatz aus.
Das soll mehrere Vorteile mit sich bringen:

* Beschleunigte Entwicklung
** Vielzahl an Entwicklungstools
** Große Anzahl an Sensortreibern

* Einfacher Einsatz
** Effiziente und effektive Nachrichtenkommunikation
** Portable und weniger Abhängigkeiten

* Vereinfachte Implementierung in eigene Fahrzeuge
** Plug-and-Play-System
** ApolloAuto verwendet das default-open-source runtime framework



//Wichtige, teure, große oder riskante Architektur- oder Entwurfsentscheidungen inklusive der jeweiligen Begründungen.
//Mit "Entscheidungen" meinen wir hier die Auswahl einer von mehreren Alternativen unter vorgegebenen Kriterien.
//
//Wägen Sie ab, inwiefern Sie Entscheidungen hier zentral beschreiben, oder wo eine lokale Beschreibung (z.B. in der Whitebox-Sicht von Bausteinen) sinnvoller ist.
//Vermeiden Sie Redundanz.
//Verweisen Sie evtl. auf Abschnitt 4, wo schon grundlegende strategische Entscheidungen beschrieben wurden.
//
//.Motivation
//Stakeholder des Systems sollten wichtige Entscheidungen verstehen und nachvollziehen können.
//
//.Form
//Verschiedene Möglichkeiten:
//
//* Liste oder Tabelle, nach Wichtigkeit und Tragweite der Entscheidungen geordnet
//* ausführlicher in Form einzelner Unterkapitel je Entscheidung
//* ADR (http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Architecture Decision Record]) für jede wichtige Entscheidung
