[[section-technical-risks]]
== Risiken und technische Schulden

"Risikomanagement ist Projektmanagement für Erwachsene."
-- Tim Lister, Atlantic Systems Guild

Eine nach Prioritäten geordnete Liste der erkannten Architekturrisiken und/oder technischen Schulden.

=== Aufwand der Implementierung
Die Implementierung von ApolloAuto ist grundsätzlich sehr komplex. Es müssen alle Hardware- und Softwareanforderungen erfüllt werden, die in den Randbedingungen definiert wurden.
Das umfasst sowohl das Setup des Fahrzeugs selbst, als auch die Einrichtung des Rechners.

.Risikominderung
Installationsanleitungen und Treiber werden in ApolloAuto gestellt.

=== Komplexes Gesamtsystem
Für die Entwicklung des Gesamtsystems ist es von großer Bedeutung, sicherzustellen, dass durch Weiterentwicklungen dieses komplexe System nicht funktionsunfähig wird.

.Risikominderung
Funktionsgruppen werden in Module unterteilt, die klar voneinander getrennte Aufgaben haben.
Des Weiteren wurde für eine Weiterentwicklung mit dem Ziel des Level 4 autonomen Fahrens mit CyberRT ein eigenes Framework konzipiert, welches extra für autonom fahrende Autos entworfen wurde.